# Dockerfile (백엔드)
# 베이스 이미지 설정
FROM python:3.12

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 파일 복사
COPY ./requirements.txt /app/requirements.txt

# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . /app

# 포트 설정
EXPOSE 8000

# FastAPI 서버 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
